package main

// DO NOT EDIT, this file is generated by hover at compile-time for the gcn_webview plugin.

import (
	"github.com/asticode/go-astikit"
	"github.com/asticode/go-astilectron"
	gcn_webview "github.com/getcouragenow/plugins/webview/gcn_webview/go"
	flutter "github.com/go-flutter-desktop/go-flutter"
)

func init() {
	// Only the init function can be tweaked by plugin maker.
	options = append(options, flutter.AddPlugin(&gcn_webview.GcnWebviewPlugin{
		Options: astilectron.Options{
			AppName:           "Webview",
			BaseDirectoryPath: "build",
		},
		WindowsOptions: &astilectron.WindowOptions{
			Center: astikit.BoolPtr(true),
			Height: astikit.IntPtr(700),
			Width:  astikit.IntPtr(700),
			WebPreferences: &astilectron.WebPreferences{
				Webaudio: astikit.BoolPtr(true),
				Webgl:    astikit.BoolPtr(true),
			},
		},
	}))
}
