# PDF Printer


# https://github.com/apple/cups
01: 
	# print to default printer
	#mac works
	lp -o media=A4 -o resolution=600dpi sample.pdf
	# mac works
	lpr -o media=A4 -o resolution=600dpi sample.pdf
02: 
	# command to list the available printers:
	lpinfo -v
03:
	# command to list all of the available drivers
	lpinfo -m
04:
	# https://superuser.com/questions/177445/how-to-list-printer-names-acceptable-for-use-with-lpr
	# i think google cloud parses this.
	lpstat -p -d
	
